name: Deploy DEV

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: 
    - self-hosted
    - dev-server

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t my-nodejs-app .
      - run: docker run -d -p 4000:4000 my-nodejs-app

